### ISSUE TITLE
stack_rasters() returns error when using SpatRasters

### ISSUE THREAD

**Issue by mateuszrydzik** [Permian-Global-Research/rsi#12]
According to the documentation, we can pass in `stack_rasters()` either SpatRaster objects or file paths. I tried to create a VRT with SpatRasters, but I encountered an error:

``` r
sa_march_rast <- terra::rast(sa_march)
sa_october_rast <- terra::rast(sa_october)

stack <- stack_rasters(
    c(
        sa_march_rast,
        sa_october_rast
    ),
    tempfile(fileext = ".vrt")
)
```
`Error: Not compatible with STRSXP: [type=S4].`

When i pass in file paths, it works perfectly well. From what I found in `stack_rasters()` function https://github.com/Permian-Global-Research/rsi/blob/main/R/stack_rasters.R#L73 , in this line it tries to create an input raster as a SpatRaster. So when I pass in SpatRaster as `rasters` argument, and then it tries to create a SpatRaster out of it, it could lead to this error.

I found similar cases here https://github.com/Permian-Global-Research/rsi/blob/main/R/stack_rasters.R#L110-L112 and here https://github.com/Permian-Global-Research/rsi/blob/main/R/stack_rasters.R#L153-L155

Here's the full code to reproduce the error

``` r
library(rsi)
library(sf)
library(terra)

san_antonio <- st_point(c(-98.491142, 29.424349))
san_antonio <- st_set_crs(st_sfc(san_antonio), 4326)
san_antonio <- st_buffer(st_transform(san_antonio, 3081), 5000)

sa_march <- get_sentinel2_imagery(
    san_antonio,
    start_date = "2023-03-01",
    end_date = "2023-03-31",
    output_filename = tempfile(fileext = ".tif")
)

sa_october <- get_sentinel2_imagery(
    san_antonio,
    start_date = "2023-10-01",
    end_date = "2023-10-31",
    output_filename = tempfile(fileext = ".tif")
)

sa_march_rast <- terra::rast(sa_march)
sa_october_rast <- terra::rast(sa_october)

# using file paths, it works
stack <- stack_rasters(
    c(
        sa_march,
        sa_october
    ),
    tempfile(fileext = ".vrt")
)

# using SpatRasters, it does not work
stack <- stack_rasters(
    c(
        sa_march_rast,
        sa_october_rast
    ),
    tempfile(fileext = ".vrt")
)

```

**Comment by mikemahoney218** [comment]
Thanks! I'm assuming it's useful for you to create these VRTs from SpatRasters, not just files? I'm asking because right now I think this is a documentation bug -- I actually intended for this to only accept file paths, and it's a copy and paste mistake that the docs say otherwise -- but if it'd be useful for this function to also write those rasters out (which would be necessary to build the VRT) then that's an easy feature to add.

**Comment by mateuszrydzik** [comment]
Not really, it's just something I found while testing. Right now it makes sense, as rsi's functions return file paths rather than SpatRaster. But I guess when more people get to use rsi and create more use cases, this issue might resurface

**Comment by mikemahoney218** [comment]
Alright! For now I'm going to fix the documentation (not this week -- I'm at a conference) and consider that "fixed". If you or anyone reading this in the future has a use-case for passing SpatRaster objects directly though, feel free to either comment on this issue or open a new one -- I'm open to the possibility, just don't currently see when it would be useful!
