### ISSUE TITLE
Time to make public. 

### ISSUE THREAD

**Issue by h-a-graham** [Permian-Global-Research/rsi#2]
Hey @mikemahoney218 we now have permission to make this package open using an Apache license. It would be great to hear your thoughts on the next steps and timeline for this - happy to take your lead here. I think general preference on our end is to make open, for us to share with the R community/our networks, generate some wider testing with the aim for CRAN submission in the not too distant future.

**Comment by h-a-graham** [comment]
Great - so, we're public! 

Agreed that makes sense for sure.

**Comment by h-a-graham** [comment]
Oh minor update -  can we change the license badge on the README? I was going to submit a PR but I wasn't sure on how the badge should be generated...

**Comment by mikemahoney218** [comment]
Whoops -- thanks! Will fix now...
