### ISSUE TITLE
`get_stac_data()` should error more nicely when 0 items are found

### ISSUE THREAD

**Issue by mikemahoney218** [Permian-Global-Research/rsi#26]
Just gave myself a minor heart attack with this one, thinking there was an error in the package I just sent to CRAN rather than simple user error.

If 0 items are returned from a query (in the below case, because there's not currently any lcmap data from 2022), rsi returns an unfortunate GDAL-level error:

``` r
aoi <- sf::st_point(c(-74.912131, 44.080410))
aoi <- sf::st_set_crs(sf::st_sfc(aoi), 4326)
aoi <- sf::st_buffer(sf::st_transform(aoi, 5070), 1000)

library(rsi)
lcpri <- get_stac_data(
  aoi,
  start_date = "2022-01-01",
  end_date = "2022-12-31",
  asset_names = "lcpri",
  stac_source = "https://planetarycomputer.microsoft.com/api/stac/v1/",
  collection = "usgs-lcmap-conus-v13",
  output_filename = tempfile(fileext = ".tif"),
)
#> Warning in CPL_gdalwarp(source, destination, options, oo, doo, config_options,
#> : GDAL Error 5: Missing url parameter

#> Warning in CPL_gdalwarp(source, destination, options, oo, doo, config_options,
#> : GDAL Error 5: Missing url parameter
#> Warning in CPL_gdalwarp(source, destination, options, oo, doo, config_options,
#> : GDAL Message 1: HTTP response code on : 0
#> Warning in CPL_gdalwarp(source, destination, options, oo, doo, config_options,
#> : GDAL Error 5: Missing url parameter

#> Warning in CPL_gdalwarp(source, destination, options, oo, doo, config_options,
#> : GDAL Error 5: Missing url parameter
#> Error in sf::gdal_utils("warp", source = item_urls, destination = out_file, : gdal_utils warp: an error occured
```

<sup>Created on 2024-01-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

We should fail on, effectively, `stopifnot(length(items$features))` -- with a nicer (classed!) error indicating that 0 items were returned.

**Comment by mateuszrydzik** [comment]
Is it possible to handle other exceptions that also result in GDAL error? In addition to incorrect dates, incorrect collection or asset names can also cause these GDAL error. Could rsi check if these names are correct, based on data fetched from the STAC source? I'm not sure about the potential impact on the speed of this function, though


One of the examples that is already implemented is when an incorrect URL is given
```
Error: Error while requesting 'https://thisiswrong/api/stac/v1/'. 
Could not resolve host: thisiswrong
```

**Comment by mikemahoney218** [comment]
My thinking is that I'm going to raise a generic error when 0 items are returned by a query (effectively, `rlang::abort("0 items were returned for this combination of collection, date range, and AOI")`) -- which should catch all those other cases, but _won't_ tell you which argument in particular was the issue. Hopefully it _will_ give you pointers on what to double-check though.

**Comment by mateuszrydzik** [comment]
Good idea, this won't affect efficiency, and I don't think there are more than those few arguments that could cause this error, so the user should be able to check them if something goes wrong.
