### ISSUE TITLE
`landsat_mask_function()` masks out water bodies

### ISSUE THREAD

**Issue by mateuszrydzik** [Permian-Global-Research/rsi#37]
this is more of a question rather than an issue

i have noticed that when downloading data for the same area using `get_*_imagery()`, landsat images have all water bodies masked out, while sentinel 2 keeps seas, oceans etc. 

on the left, product downloaded using `get_landsat_imagery()`, on the right - using `get_sentinel2_imagery()`
<img src="https://github.com/Permian-Global-Research/rsi/assets/62845725/1df19631-689a-4a98-8102-6e2e666f78da" alt="image" width="300" height="auto"> <img src="https://github.com/Permian-Global-Research/rsi/assets/62845725/f08b5c38-e41b-40b8-a675-63de77b6da26" alt="image" width="300" height="auto">

Is there a particular reason why the 21824 pixel value is chosen in `landsat_mask_function()`? i tried to change it to other values listed in the pdf that is linked here: https://github.com/Permian-Global-Research/rsi/blob/main/R/mask_functions.R#L62-L66, but this results in masking out the remaining pixels. i'm really interested in the water bodies, so maybe it might be easier for me to just skip the masking process when downloading images?

**Comment by mikemahoney218** [comment]
I should make this more clear in the documentation. The original purpose of this package was forest carbon modeling, and as there's no forest in waterbodies this mask was a straightforward way to get rid of all non-usable data. There's a code comment in the source of the masking function that links to the other values of the qa pixel -- which might help you construct a better masking function in the short term. But I should clarify this in the docs (and consider providing other built-in masks)

**Comment by mateuszrydzik** [comment]
I've had a chance to get back to this topic. I have found the mask function that works the best for my case. It selects pixels classified as either land without clouds or water without clouds. I'll post the function here in case anyone needs it in the future.

```{r}
landsat_lw_mask_function <- function(raster) {
  raster == 21824 | raster == 21952
}
```

![image](https://github.com/Permian-Global-Research/rsi/assets/62845725/377e83a9-9a5a-4d87-bc7e-d45851ff96a3)

**Comment by mikemahoney218** [comment]
Thanks! I'll look at adding this as an option to the built-in mask function

**Comment by mikemahoney218** [comment]
Slowly but surely:
``` r
boston <- sf::st_point(c(-71.0610279, 42.361697)) |> 
  sf::st_sfc(crs = 4326) |> 
  sf::st_transform(2249) |> 
  sf::st_buffer(10000)

boston_landsat <- rsi::get_landsat_imagery(
  boston,
  "2022-06-01",
  "2022-07-01",
  output_filename = tempfile(fileext = ".tif")
)

terra::rast(boston_landsat) |> terra::plot()
```

![](https://i.imgur.com/YbWW9aT.png)

``` r

boston_landsat_both <- rsi::get_landsat_imagery(
  boston,
  "2022-06-01",
  "2022-07-01",
  output_filename = tempfile(fileext = ".tif"),
  mask_function = \(r) rsi::landsat_mask_function(r, include = "both")
)

terra::rast(boston_landsat_both) |> terra::plot()
```

![](https://i.imgur.com/bCacfGs.png)

<sup>Created on 2024-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

@mateuszrydzik , can you share where you found the 21952 code any chance? I had no luck finding that code when I searched.

**Comment by mateuszrydzik** [comment]
I found it in this blog post: https://medium.com/data-and-beyond/removing-cloud-cover-from-satellite-imagery-a-toy-example-using-landsat-8-9-ca52ff23d65e

At first, I tried using a pixel value of 21888, like mentioned in the documentation, but it still removed water bodies. It's a shame that the author of this post hasn't explained how they came up with that value or where they found it.
