### ISSUE TITLE
Mention in CRAN Spatial Task View

### ISSUE THREAD

**Issue by kadyb** [Permian-Global-Research/rsi#38]
Could you consider adding information about this package to [CRAN Spatial Task View](https://github.com/cran-task-views/Spatial/)?

**Comment by mikemahoney218** [comment]
I've been meaning to -- got as far as forking the repo and starting to write a bullet before getting distracted. I'll do this in the near future

**Comment by mikemahoney218** [comment]
Opened https://github.com/cran-task-views/Spatial/pull/69 to resolve this

**Comment by rsbivand** [comment]
@mikemahoney218 Thanks for helping out!

**Comment by mikemahoney218** [comment]
Thanks for maintaining the task view!
