### ISSUE TITLE
Query for Calculation of some Indexes

### ISSUE THREAD

**Issue by alkimj** [Permian-Global-Research/rsi#60]
Dear contributors, 

I am reaching out to you regarding your excellent "rsi" R package, which I have been utilizing for my research activities.

I have encountered a challenge with the calculation of vegetation indexes such as EVI, ARVI, EBI, and others, particularly concerning parameters such as gamma, g, alpha, lambdaN, and epsilon, ecc. Despite thoroughly reviewing the documentation, I have been unable to find any information on these parameters.
In particular, the errors have the following type of message: **Error in eval(calc) : object 'gamma' not found**

Could you please provide some guidance on how to address this issue?

Thank you in advance for your assistance.

Best regards

**Comment by mikemahoney218** [comment]
These parameters are coming from the [Awesome Spectral Indices](https://awesome-ee-spectral-indices.readthedocs.io/en/latest/) project, which uses these terms for external data needed to calculate each index. As for how you'd find this external data, that's going to be specific to the indices you're interested in -- check out the `doi` column of `spectral_indices()` for a reference for each index which might be helpful (for instance, [here's the reference for EVI](https://awesome-ee-spectral-indices.readthedocs.io/en/latest/)), or check out ASI's [interactive list](https://awesome-ee-spectral-indices.readthedocs.io/en/latest/list.html).

That's going to take a good amount of time for each index you're interested in. It sounds like you're trying to calculate a lot of indices all at once, however, and don't care as much about the details of individual indices. In that case, you can get the set of indices that can be calculated from your imagery, without needing any extra information, using:

```filter_bands(bands = names(terra::rast(your_imagery)))```

You can pass that directly to the `indices` argument of `calculate_indices()` to only calculate the indices you've got all the information for.

As a note to self: this is demonstrated in [the Getting Started vignette](https://permian-global-research.github.io/rsi/articles/rsi.html), but is poorly signposted and should probably be in an example in `calculate_indices()` and in the "How Can I" vignette as well!
