### ISSUE TITLE
Add overwrite argument to calculate_indices()

### ISSUE THREAD

**Issue by Cidree** [Permian-Global-Research/rsi#69]
Hello!

I wanted to suggest to add the `overwrite` argument to the `calculate_indices()` function. It can be tedious to change `output_filename` all the time you run the code, or manually delete it. What do you think?

**Comment by mikemahoney218** [comment]
Definitely, thanks for pointing it out -- will be fixed in #70

**Comment by mikemahoney218** [comment]
Thanks for the report! Fixed on `main`
