### ISSUE TITLE
How to keep scene classification layer when using get_sentinel2_imagery

### ISSUE THREAD

**Issue by laurenkwick** [Permian-Global-Research/rsi#71]
Hi!

This is a great library and has been extremely helpful to work with geospatial data. I was wondering if there was a good way to copy and adjust rsi band mapping objects? 

For sentinel-2 data, I would like to preserve the "scl" band. In the rsi band mapping object `rsi::sentinel2_band_mapping$aws_v1`, the "scl" band is defined in the mask_band attribute, but it is not in the band mapping vector. I have a scenario where I do not want to apply the masking function in the get_sentinel2_imagery function, but I still want to save the "scl" band as an asset. Is it possible to do this? 

This is what the band mapping object currently looks like:
```r
An rsi band mapping object with attributes:
names mask_band mask_function stac_source collection_name query_function download_function class

    blue  coastal    green      nir    nir08    nir09      red rededge1 rededge2 rededge3   swir16   swir22 
     "B"      "A"      "G"      "N"     "N2"     "WV"      "R"    "RE1"    "RE2"    "RE3"     "S1"     "S2" 
```
And this is what I want it to look like: 
```r
An rsi band mapping object with attributes:
names mask_band mask_function stac_source collection_name query_function download_function class

    blue  coastal    green      nir    nir08    nir09      red rededge1 rededge2 rededge3   swir16   swir22  scl
     "B"      "A"      "G"      "N"     "N2"     "WV"      "R"    "RE1"    "RE2"    "RE3"     "S1"     "S2"   "SCL"
```

I cannot add another element to the band mapping object without it removing all of the other attributes (i.e. stac_source, collection_name, etc.). So right now, I'm using this workaround where I create a custom named vector and then manually define the parameters that would look normally be looking at the `asset_names` argument:

```r
  s2_vals <- c("B","A","G","N","N2","WV","R","RE1","RE2","RE3","S1","S2","SCL")
  names(s2_vals) <- c("blue", "coastal", "green", "nir", "nir08", "nir09", "red", 
                      "rededge1", "rededge2", "rededge3", "swir16", "swir22", "scl")
  s2_asset <- rsi::sentinel2_band_mapping$aws_v1
  
  # Retrieve raster data
  # Add a small buffer to aoi layer to get all pixels within the aoi boundary after reprojection (see rsi::get_stac_data help text)
  image <- rsi::get_sentinel2_imagery(
    aoi = sf::st_buffer(aoi_search, dist=50), 
    start_date = dates[1],
    end_date = dates[2],
    asset_names = s2_vals,
    stac_source = attr(s2_asset, "stac_source"),
    collection = attr(s2_asset, "collection_name"),
    query_function = attr(s2_asset, "query_function"),
    sign_function = attr(s2_asset, "sign_function"),
    composite_function = NULL,
    output_filename = tempfile(pattern="S2img", tmpdir=tempdir(), fileext=".tif")
)
```

I just wanted to see if there was a better way of adding the "scl" band as an asset at this time. 
Thank you!

**Comment by mikemahoney218** [comment]
Thanks! This will be fixed by #72

**Comment by mikemahoney218** [comment]
(or, to answer your actual question -- there isn't a better way _yet_, but soon in dev running `c(band_map, scl = scl)` will get you there)

**Comment by mikemahoney218** [comment]
This is now in `main`:

``` r
c(rsi::sentinel2_band_mapping$planetary_computer_v1, scl = "scl")
#>   B01   B02   B03   B04   B05   B06   B07   B08   B8A   B09   B11   B12   scl 
#>   "A"   "B"   "G"   "R" "RE1" "RE2" "RE3"   "N"  "N2"  "WV"  "S1"  "S2" "scl"
```

<sup>Created on 2024-06-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

If you don't name the additional assets, the asset name gets used as the output band name:

``` r
identical(
  c(rsi::sentinel2_band_mapping$planetary_computer_v1, scl = "scl"),
  c(rsi::sentinel2_band_mapping$planetary_computer_v1, "scl")
)
#> [1] FALSE
```

<sup>Created on 2024-06-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Thanks again for the report!
